### ISSUE TITLE
OOM when using GAS>1

### ISSUE THREAD

**Issue by kallewoof** [tdrussell/qlora-pipe#36]
I have been able to use any GAS value without any noticeable VRAM changes in the past, but recently, I have seen very weirdly timed OOMs. The first one happened with GAS=4 after over 500 steps, at around epoch 1.2 or so, i.e. the model had trained on everything once already successfully and was doing it again when it ran out of VRAM. Resuming the run resulted in OOM after some dozen or so steps. This is with pipeline_stages=2, i.e. the model trains each batch sequentially.

I have seen intermittent OOMs after this, for different models, around step 50-60 again with GAS=4. The exact same setup with GAS=1 does not OOM.

I wonder if the batching stuff could be the reason, but IIUC they should be identical for the same step across epochs, which means it should have OOM'd during epoch 1. Also, the code literally puts the biggest fattest batch at step 1 to ensure OOM happens early, and yet it continues on for 500+ steps before finally breaking.

It is possible that there is some subtle form of leak somewhere, but if that was the case, I would assume that the resume of the 500+ step run above would run for another 500 or so steps before crashing, but it didn't.

**Comment by kallewoof** [comment]
Don't think this is qlora-pipe related.

**Comment by tdrussell** [comment]
I can share a few things that might be the cause.

First, are you training with variable batch sizes? (meaning using batch_size_tokens along with variable length data) Because tensors are different sizes each step, it may cause more memory fragmentation. And this could theoretically get worse as time goes on. Might be worth implementing sample packing at some point to avoid this.

Another thing, GAS > 1 uses a tiny bit more memory, since it needs some buffers proportional to the maximum number of in-flight forward and backward passes. This is capped by your number of pipeline stages though.

I have seen in the past that resuming from checkpoint can use a very small amount of additional VRAM. Something in deepspeed or pytorch leaks a bit of memory. If you search you can find others reporting similar issues.

For what it's worth, a few weeks ago (on a commit prior to the most recent round of changes, if that matters), I trained a qlora on mistral-large across 4 4090s. This was with multiple resumes. Each GPU had a couple of GB of free memory, and I recall the usage being very consistent. This was with fixed sized batches though.

**Comment by kallewoof** [comment]
Thanks for the suggestions! I am using `batch_sizer_tokens` and variable length data, yes. I'm not sure how that would cause memory fragmentation. What's boggling to me is that qlora-pipe trained successfully on the batch once and then failed the second time.

**Comment by jukofyork** [comment]
> I can share a few things that might be the cause.
> 
 > For what it's worth, a few weeks ago (on a commit prior to the most recent round of changes, if that matters), I trained a qlora on mistral-large across 4 4090s. This was with multiple resumes. Each GPU had a couple of GB of free memory, and I recall the usage being very consistent. This was with fixed sized batches though.

Yeah, I'm currently training a qlora on mistral-large across 3 machines each with 2xA6000 (ie: `pipeline_stages = 2`) and I'm seeing steady 45/48GB used on each machine. I'm the past when I've OOMed it's always been after the first eval step so fingers crossed it will stay like this as only 1/4 of the way through so far.

**Comment by kallewoof** [comment]
I have only ever seen qlora-pipe crash on the first step before. It crashing on step 500-something was pretty disconcerting but I am also juggling a bunch of the dependencies as latest-github-commit versions, so I bet the issue is in some bug there. I just resorted to using `activation_checkpointing = 'unsloth'` which is slower but at least it doesn't OOM.

**Comment by jukofyork** [comment]
Did you ever get the the bottom of this?

I've had a weird one where it keeps running 1 more step at the end (`"step:    563 /   562 loss: ..."`), and before your fix to use `min_lr`; I tried using with cosine annealed schedule and (I *think*) the `lr` went negative (ie: gradient *ascent*) on this last step and screwed the model over :/

I'm not sure if it's because I've started using `eval_after_last_step = true`, but IIRC the time the model got screwed I wasn't actually using this setting...

I don't remember it running these extra steps before, but I guess it could be related to batch size and I just happened to get lucky before and the total number of batches was an even multiple of my 6 GPUs I'm running it on?

**Comment by kallewoof** [comment]
> Did you ever get the the bottom of this?

Work kept me away so I haven't really done anything qlora-pipe related recently. Definitely intend to look closer at this when I get the chance.

> I've had a weird one where it keeps running 1 more step at the end (eg: `"step: 563 / 562 loss: ..."`), and before your fix to use `min_lr`; I tried using with cosine annealed schedule and (I _think_) the `lr` went negative (ie: gradient _ascent_) on this last step and screwed the model over :/

I always see that extra step these days. Like you, I don't recall seeing it in the past, but I don't save the trainer output for runs so I can't check. Kinda tempted to propose a built-in tee feature to just log everything to stdout AND to the out-dir/trainer.log.

> I'm not sure if it's because I've started using `eval_after_last_step = true`, but IIRC the time the model got screwed I wasn't actually using this setting...

That setting should not affect training at all, no.

> I don't remember it running these extra steps before, but I guess it could be related to batch size and I just happened to get lucky before and the total number of batches was an even multiple of my 6 GPUs I'm running it on?

Don't think so. I consistently see that extra step on my end.

**Comment by jukofyork** [comment]
I've been looking to see where this extra step is coming from and nothing stands out in the code :/

Do you have any logs saved that might narrow down when it started occurring?

(Sadly I haven't been saving any, but will start using your suggestion of piping into `tee` now)

**Comment by kallewoof** [comment]
> I've been looking to see where this extra step is coming from and nothing stands out in the code :/

I assume it is
```python
steps_per_epoch = len(train_dataloader) // model_engine.gradient_accumulation_steps()
```
which will be truncated unless `len(train_dataloader)` is evenly divisible by the GAS. Easy fix, I think? Just ceil it. I'll PR.

This would explain why it happens sometimes and not others. I used GAS 1 for a long time as I heard > 1 was unstable. I then started using a higher value because I was recommended an effective BS of ~16-32.

**Comment by tdrussell** [comment]
Extra training step on epoch end is fixed by e9b1bfb.

**Comment by kallewoof** [comment]
I had another OOM, this time at step 9,
```
before GAS splitting, batch size: 4, total tokens: 61440
```
whereas it succeeded at step 1 with
```
before GAS splitting, batch size: 4, total tokens: 65536
```
... I have no idea what is going on. Trace:
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/qlora-pipe/train.py", line 662, in <module>
[rank1]:     metrics = model_engine.train_batch()
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/qlora-pipe/engine.py", line 77, in train_batch
[rank1]:     self._exec_schedule(sched)
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 1434, in _exec_schedule
[rank1]:     self._exec_instr(**cmd.kwargs)
[rank1]:   File "/qlora-pipe/engine.py", line 263, in _exec_forward_pass
[rank1]:     outputs = super(PipelineEngine, self).forward(inputs)
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1855, in forward
[rank1]:     loss = self.module(*inputs, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/module.py", line 367, in forward
[rank1]:     x = exec_range_func(start_idx, end_idx)(*x)
[rank1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/module.py", line 344, in exec_func
[rank1]:     inputs = layer(inputs)
[rank1]:              ^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/qlora-pipe/llama_pipe.py", line 86, in forward
[rank1]:     return self.lm_head(hidden_states*self.logit_scale), labels
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/nn/modules/linear.py", line 117, in forward
[rank1]:     return F.linear(input, self.weight, self.bias)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.77 GiB. GPU 1 has a total capacity of 23.58 GiB of which 2.47 GiB is free. Including non-PyTorch memory, this process has 21.07 GiB memory in use. Of the allocated memory 15.48 GiB is allocated by PyTorch, and 5.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by jukofyork** [comment]
```python
return self.lm_head(hidden_states*self.logit_scale), labels
```

If you aren't training a Cohere model then it might be worth bypassing this:

```python
If logit_scale == 1.0:
    return self.lm_head(hidden_states), labels
else:
    return self.lm_head(hidden_states*self.logit_scale), labels
```

and see if that helps.

**Comment by kallewoof** [comment]
> ```python
> return self.lm_head(hidden_states*self.logit_scale), labels
> ```
> 
> If you aren't training a Cohere model then it might be worth bypassing this:
> 
> ```python
> If logit_scale == 1.0:
>     return self.lm_head(hidden_states), labels
> else:
>     return self.lm_head(hidden_states*self.logit_scale), labels
> ```
> 
> and see if that helps.

Hm. I dropped params to get around it, but if I see a similar trace again I'll give it a shot. FWIW, my main ickiness with this issue is that it is failing despite step 1 succeeding. That really bugs me a lot, since step 1 should be maximally demanding and nothing else is really parallel (step-to-step wise) so there shouldn't be any weird edge cases anywhere.

**Comment by jukofyork** [comment]
> Hm. I dropped params to get around it, but if I see a similar trace again I'll give it a shot. FWIW, my main ickiness with this issue is that it is failing despite step 1 succeeding. That really bugs me a lot, since step 1 should be maximally demanding and nothing else is really parallel (step-to-step wise) so there shouldn't be any weird edge cases anywhere.

I've just set off a `bf16` training run on `command-r-plus` over 6 stages and so far (on step 10) the VRAM use still seems to be staying constant, with the closest being `47102MiB /  49140MiB`. I'll report back if it OOMs (hopefully not!).

**Comment by kallewoof** [comment]
Will open a new issue if this resurfaces.
